apiVersion: v1
kind: Pod
metadata:
  name: Jenkins-slave-pod
  namespace: jenkins
  labels:
    name: Jenkins-slave
spec:
  serviceAccount: jenkins
  containers:
  - name: shell
    image: alpine
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker/
  - name: kustomize
    image: nekottyo/kustomize-kubeval
    command:
    - cat
    tty: true
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
